GET http://localhost:3000/movies
###API 1


POST http://localhost:3000/movies
Content-Type: application/json

{
    "directorId": 7,
    "movieName": "Jawan",
    "leadActor": "Shahrukh Khan"
}
###API2



GET http://localhost:3000/movies/46
###API3

PUT http://localhost:3000/movies/50
Content-Type: application/json

{
    "movieId": "46",
    "directorId": "7",
    "movieName": "Jawaan",
    "leadActor": "Shahrukh Khan"
}
###API4

DELETE http://localhost:3000/movies/48
###API5


GET http://localhost:3000/directors/
###API6

GET http://localhost:3000/directors/4/movies/
###API7